import { Roboto } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import "@fortawesome/fontawesome-svg-core/styles.css";

import { config } from "@fortawesome/fontawesome-svg-core";
import MainLayout from "@/components/Layout/MainLayout";
import Navbar from "@/components/Layout/Navbar";
import Sidebar from "@/components/Layout/Sidebar";
import Footer from "@/components/Layout/Footer";
import { Toaster } from "@/components/ui/toaster";
import ProgressProvider from "@/components/Layout/ProgressProvider";
config.autoAddCss = false;

const roboto = Roboto({
  weight: ["400", "500", "700", "900"],
  subsets: ["latin"],
  variable: "--font-roboto",
  // display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={cn("bg-gray-200 antialiased font-sans", roboto.variable)}
      >
        <ProgressProvider>
          <Navbar />
          <Sidebar />
          <MainLayout>{children}</MainLayout>
          {/* <Footer /> */}
          <Toaster />
        </ProgressProvider>
      </body>
    </html>
  );
}
